### importing necessary libraries

In [168]:
import pandas as pd 
import numpy as np

### importing dataset

In [169]:
df = pd.read_csv('https://raw.githubusercontent.com/gurmindero7/test_datasets/refs/heads/main/diabetes_prediction_dataset.csv')

### Checking dataset information

In [170]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,41.885856,0.07485,0.039420,27.320767,5.527507,138.058060,0.085000
std,22.516840,0.26315,0.194593,6.636783,1.070672,40.708136,0.278883
min,0.080000,0.00000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,24.000000,0.00000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,43.000000,0.00000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,60.000000,0.00000,0.000000,29.580000,6.200000,159.000000,0.000000
max,80.000000,1.00000,1.000000,95.690000,9.000000,300.000000,1.000000

In [171]:
df.head(4)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0

given dataset has 100000 rows and 9 columns

target variable diabetes(0: no diabetes, 1: diabetes)

### Data Preprocessing

replacing missing, nan and undefined values with 0

In [ ]:
df.replace('?', np.nan, inplace=True)
df.replace(np.nan, 0, inplace=True)

converting categorical variable into numerical using one-hot encoding
particularly converting gender, M: 1 and f:0

In [173]:
df['gender'] = df['gender'].map({'Male': 1, 'Female': 0})

smoking history also needs to be converted to numerical values
checking the distinct smoking_history values

In [174]:
df['smoking_history'].unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [175]:
df['smoking_history']= df['smoking_history'].map({'never': 0, 'formerly': 1, 'current': 2, 'not current': 3, 'ever': 4})

In [176]:
df.head(5)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0.0,80.0,0,1,0.0,25.19,6.6,140,0
1,0.0,54.0,0,0,NaN,27.32,6.6,80,0
2,1.0,28.0,0,0,0.0,27.32,5.7,158,0
3,0.0,36.0,0,0,2.0,23.45,5.0,155,0
4,1.0,76.0,1,1,2.0,20.14,4.8,155,0

In [177]:
df.head(2)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0.0,80.0,0,1,0.0,25.19,6.6,140,0
1,0.0,54.0,0,0,NaN,27.32,6.6,80,0

In [178]:
df.describe()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
count,99982.000000,100000.000000,100000.00000,100000.000000,54832.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,0.414375,41.885856,0.07485,0.039420,0.983532,27.320767,5.527507,138.058060,0.085000
std,0.492616,22.516840,0.26315,0.194593,1.391647,6.636783,1.070672,40.708136,0.278883
min,0.000000,0.080000,0.00000,0.000000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,0.000000,24.000000,0.00000,0.000000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,0.000000,43.000000,0.00000,0.000000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,1.000000,60.000000,0.00000,0.000000,2.000000,29.580000,6.200000,159.000000,0.000000
max,1.000000,80.000000,1.00000,1.000000,4.000000,95.690000,9.000000,300.000000,1.000000

Normalizing the data
describe() method shows us that the data is not normalized. Because the age ranges between 0.008-80.0, BMI ranges from 10-96 and blood glucose level ranges from 80-300

so, we need to normalize

In [179]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[['age']] = scaler.fit_transform(df[['age']])
df[['bmi']] = scaler.fit_transform(df[['bmi']])
df[['blood_glucose_level']] = scaler.fit_transform(df[['blood_glucose_level']])

### Building the Machine learning classification model

splitting the data into training and test sets with 80/20 rule(80% training and 20% test data)

In [180]:
from sklearn.model_selection import train_test_split

X = df.drop('diabetes', axis=1)
y = df['diabetes']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Training model using random forest and decision tree

random forest

In [181]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

decision tree

In [183]:
# trainig model for decision tree classifier
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

Model evaluation

In [187]:
from sklearn.metrics import classification_report, accuracy_score

dt_predictions = dt_model.predict(X_test)
print("Decision Tree Classification Report:")
print(classification_report(y_test, dt_predictions))
print("Decision Tree Accuracy:")
print(accuracy_score(y_test, dt_predictions))

Decision Tree Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.97      0.97     18292
           1       0.72      0.74      0.73      1708

    accuracy                           0.95     20000
   macro avg       0.85      0.86      0.85     20000
weighted avg       0.95      0.95      0.95     20000

Decision Tree Accuracy:
0.9537

In medical field we need to worry about the precision of the model. as we can observe the precision is really good. so, using the random forest model was a good choice

Random Forrest was used because it uses ensemble learning techniqe to combine result from various decision trees and give us the best result

the second model used was the decision tree because it is easy to visulize and interpret this one