In [57]:
import pandas as pd 
import numpy as np

importing dataset

In [58]:
df = pd.read_csv(
    'https://raw.githubusercontent.com/gurmindero7/test_datasets/refs/heads/main/employee_data.csv'
)
df.head()

   EmployeeID             Name  Department    Salary JoiningDate      Status
0        7970              NaN  Operations   44168.0  2023-04-16  Terminated
1        1752   Shannon Franco          HR   80140.0  2016-08-22  Terminated
2        8478              NaN          HR  144316.0  2023-11-04  Terminated
3        5157  Barbara Alvarez  Operations   35075.0  2023-04-22         NaN
4        1816        Adam Cobb       Sales  142537.0  2016-05-12      Active

inspecting dataset

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeID   500 non-null    int64
 1   Name         450 non-null    object
 2   Department   450 non-null    object
 3   Salary       450 non-null    float64
 4   JoiningDate  450 non-null    object
 5   Status       450 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 23.6+ KB

removing duplicate values

In [60]:
df.drop_duplicates(inplace=True)

missing values count in each column

In [61]:
missing_values = df.isnull().sum()
missing_values

EmployeeID      0
Name           50
Department     50
Salary         50
JoiningDate    50
Status         50
dtype: int64

dropping rows with missing values

In [62]:
df.dropna(inplace=True)

checking count of missing values in the dataset after dropping missing values

In [63]:
missing_values = df.isnull().sum()
missing_values

EmployeeID     0
Name           0
Department     0
Salary         0
JoiningDate    0
Status         0
dtype: int64

joining date column into proper date format conversion

In [64]:
df['JoiningDate'] = pd.to_datetime(df['JoiningDate'], format='%Y-%m-%d')

In [65]:
df['JoiningDate']

1     2016-08-22
4     2016-05-12
6     2023-06-14
7     2016-03-29
8     2018-08-04
         ...
487   2023-06-13
488   2024-01-11
489   2016-04-01
492   2023-01-04
496   2022-09-23
Name: JoiningDate, Length: 293, dtype: datetime64[ns]

Resigned Employees

In [66]:
df['Status']

1      Terminated
4          Active
6        On Leave
7      Terminated
8        On Leave
          ...
487        Active
488        Active
489        Active
492        Active
496      Resigned
Name: Status, Length: 293, dtype: object

In [67]:
#printing only the employees with status as "resigned"
df[df['Status'] == 'Resigned']

     EmployeeID              Name   Department    Salary JoiningDate    Status
10         4786  Loretta Espinoza   Operations   75830.0  2014-12-24  Resigned
12         4245     Jamie Aguilar      Finance  137549.0  2015-06-26  Resigned
14         7189  Andrew Zimmerman      Finance  144206.0  2015-09-17  Resigned
15         6554    George Jenkins    Marketing   59831.0  2015-01-13  Resigned
18         7627   Elizabeth Owens           HR  116511.0  2023-11-03  Resigned
..          ...               ...          ...       ...         ...       ...
465        4320      Austin Smith      Finance   90910.0  2020-05-22  Resigned
480        3147       Susan Burke      Finance   63862.0  2015-01-09  Resigned
482        4816         Bryan Cox      Finance   66655.0  2020-08-30  Resigned
483        6198      Thomas Nunez   Operations  145385.0  2017-09-20  Resigned
496        3910   Douglas English  Engineering   94038.0  2022-09-23  Resigned

[77 rows x 6 columns]

In [68]:
df['Department'].value_counts()

Department
Engineering    58
HR             56
Finance        55
Sales          43
Marketing      41
Operations     40
Name: count, dtype: int64

### Average salary of employees in each department

In [69]:
departs = ['Engineering', 'HR', 'Finance', 'Sales', 'Marketing', 'Operations']
avg_salary = df.groupby('Department')['Salary'].mean()
avg_salary

Department
Engineering    99588.586207
Finance        89270.709091
HR             84595.892857
Marketing      87002.975610
Operations     95357.350000
Sales          91920.000000
Name: Salary, dtype: float64

Employees joined after 2020

In [70]:
df[df['JoiningDate'] > '2020-01-01']

,EmployeeID,Name,Department,Salary,JoiningDate,Status
6,6247,Allison Salas,Engineering,59154.0,2023-06-14,On Leave
13,1409,Mrs. Bonnie Gutierrez MD,HR,134247.0,2020-11-09,Terminated
18,7627,Elizabeth Owens,HR,116511.0,2023-11-03,Resigned
19,9152,Whitney Curtis,Engineering,55313.0,2021-10-12,Resigned
25,6853,Steve Martin,Engineering,131361.0,2022-08-12,On Leave
...,...,...,...,...,...,...
482,4816,Bryan Cox,Finance,66655.0,2020-08-30,Resigned
487,1586,Brian Kim,Engineering,66211.0,2023-06-13,Active
488,3772,Jonathan Haley,Marketing,102848.0,2024-01-11,Active
492,7210,Phillip Riley,Sales,41221.0,2023-01-04,Active
496,3910,Douglas English,Engineering,94038.0,2022-09-23,Resigned

Cleaned DataFrame

In [71]:
df

,EmployeeID,Name,Department,Salary,JoiningDate,Status
1,1752,Shannon Franco,HR,80140.0,2016-08-22,Terminated
4,1816,Adam Cobb,Sales,142537.0,2016-05-12,Active
6,6247,Allison Salas,Engineering,59154.0,2023-06-14,On Leave
7,5968,Daniel Rodriguez,Engineering,56158.0,2016-03-29,Terminated
8,3344,Scott Coleman,Operations,137031.0,2018-08-04,On Leave
...,...,...,...,...,...,...
487,1586,Brian Kim,Engineering,66211.0,2023-06-13,Active
488,3772,Jonathan Haley,Marketing,102848.0,2024-01-11,Active
489,9544,Sonya Watts,HR,31330.0,2016-04-01,Active
492,7210,Phillip Riley,Sales,41221.0,2023-01-04,Active
496,3910,Douglas English,Engineering,94038.0,2022-09-23,Resigned

Result of Analysis for given data

The dataset have a total of 500 employees data and the dataset contains 6 columns which are EmployeeID, Name, Department, Salary, JoiningDate, Status. The dataset contains 50 missing values in all the columns except EmployeeID. The dataset also contains some duplicate rows which have been removed. The dataset has been cleaned and prepared for analysis.

Data analysis makes us understand that the Enginnering department has the highest average salary and the HR department has the loweset average salary